# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-browsers-legacy

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

      - image: circleci/mysql:5.7
        command: mysqld
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: sfgpetclinic
          MYSQL_ROOT_HOST: 127.0.0.1
          MYSQL_USER: root

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: sudo apt install -y mysql-client
      - run: ps -axg | grep mysql
      - run: netstat -lnpat | grep 3306
      - run:
          name: MySQL database
          command: mysql -h 127.0.0.1 -u root -e "create database sfgpetclinic; create user 'sfgpetclinic'@'localhost' identified by 'sfgpetclinic'; grant all on sfgpetclinic.* to 'sfgpetclinic'@'localhost';"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test
